name = "taylor_series_fortran"
version = "0.1.0"
license = "MIT"
author = "DSCF-1224"
maintainer = "37315588+DSCF-1224@users.noreply.github.com"
copyright = "Copyright 2025, DSCF-1224"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false
[install]
library = false
[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

